<a href="https://colab.research.google.com/github/sujal910/Learning_PyTorch/blob/main/01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Introdution** to tensor

### **What is a Tensor?**

In PyTorch, a **Tensor** is the fundamental building block for data. Think of it as a generic container for numbers, similar to a NumPy array, but with two special superpowers:
1.  **GPU Support:** Tensors can run on video cards (GPUs) for massive speedups.
2.  **Automatic Differentiation:** Tensors can track the math operations performed on them to help calculate gradients for AI learning.

#### **The Hierarchy of Dimensions**
The word "Tensor" is the general name for arrays of any dimension:

* **0-D Tensor (Scalar):** A single number (e.g., `7`). Has magnitude but no direction.
* **1-D Tensor (Vector):** A list of numbers (e.g., `[7, 7]`). Has magnitude and direction.
* **2-D Tensor (Matrix):** A grid of numbers (rows & columns). commonly used for spreadsheets or black-and-white images.
* **3-D+ Tensor:** A cube or hyper-cube of numbers. Used for things like RGB images (Height x Width x Color) or video batches.

> **Note:** In Deep Learning, we use the word "Tensor" to refer to all of the above, regardless of how many dimensions they have.

## Starting With Tensors

In [ ]:
import torch
print(torch.__version__)

2.9.0+cpu


## Introduction to tensor

### creating a tensor




In [ ]:
# Scalar
import torch
scalar = torch.tensor(9)
scalar

tensor(9)

* In data science libraries like NumPy and PyTorch, .ndim is an attribute that tells you the number of dimensions (or axes) a data object has.



In [ ]:
scalar.ndim


0

In [ ]:
# getting tensor back as python int
scalar.item()

9

In [ ]:
# Vector
vector = torch.tensor([9,8])
vector

tensor([9, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

## Creating **MATRIX** in pytorch

In [ ]:
# A 2x3 Matrix (2 rows, 3 columns)
data = [[1, 2, 3],
        [4, 5, 6]]

MATRIX = torch.tensor(data)

MATRIX


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
MATRIX[1]

tensor([4, 5, 6])

In [ ]:
MATRIX.shape

torch.Size([2, 3])

##**TENSOR**

In [ ]:
TENSOR = torch.tensor([[[[1,2,3],
                        [7,8,9],
                        [8,9,5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [7, 8, 9],
          [8, 9, 5]]]])

### Understanding this Tensor

**1. Why is `.ndim` 4?**
You can determine dimensions by counting the opening brackets `[` before the first number appears:
* `[` (1st dim)
* `[` (2nd dim)
* `[` (3rd dim)
* `[` (4th dim)
* `1` (The data starts here)

**2. Why is `.shape` [1, 1, 3, 3]?**
This specific shape corresponds to a common image format in Deep Learning:
* **Batch Size: 1** (1 image in this group)
* **Channels: 1** (1 color channel, e.g., Grayscale)
* **Height: 3** (3 pixels high)
* **Width: 3** (3 pixels wide)

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[[1, 2, 3],
         [7, 8, 9],
         [8, 9, 5]]])