<a href="https://colab.research.google.com/github/sujal910/Learning_PyTorch/blob/main/01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introdution to tensor

# Starting With Tensors

In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


##**Introduction to tensor**

## creating a tensor




In [5]:
# Scalar
import torch
scalar = torch.tensor(9)
scalar

tensor(9)

In [8]:
'''In data science libraries like NumPy and PyTorch, .ndim is an attribute that tells you the number of dimensions (or axes) a data object has.'''
scalar.ndim


0

In [6]:
# getting tensor back as python int
scalar.item()

9

In [9]:
# Vector
vector = torch.tensor([9,8])
vector

tensor([9, 8])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

## creating matrix in pytorch

In [12]:
# A 2x3 Matrix (2 rows, 3 columns)
data = [[1, 2, 3],
        [4, 5, 6]]

MATRIX = torch.tensor(data)

MATRIX


tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
MATRIX.ndim

2

In [15]:
MATRIX[0]

tensor([1, 2, 3])

In [14]:
MATRIX[1]

tensor([4, 5, 6])

In [16]:
MATRIX.shape

torch.Size([2, 3])