<a href="https://colab.research.google.com/github/sujal910/Learning_PyTorch/blob/main/01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Introdution** to tensor

### **What is a Tensor?**

In PyTorch, a **Tensor** is the fundamental building block for data. Think of it as a generic container for numbers, similar to a NumPy array, but with two special superpowers:
1.  **GPU Support:** Tensors can run on video cards (GPUs) for massive speedups.
2.  **Automatic Differentiation:** Tensors can track the math operations performed on them to help calculate gradients for AI learning.

#### **The Hierarchy of Dimensions**
The word "Tensor" is the general name for arrays of any dimension:

* **0-D Tensor (Scalar):** A single number (e.g., `7`). Has magnitude but no direction.
* **1-D Tensor (Vector):** A list of numbers (e.g., `[7, 7]`). Has magnitude and direction.
* **2-D Tensor (Matrix):** A grid of numbers (rows & columns). commonly used for spreadsheets or black-and-white images.
* **3-D+ Tensor:** A cube or hyper-cube of numbers. Used for things like RGB images (Height x Width x Color) or video batches.

> **Note:** In Deep Learning, we use the word "Tensor" to refer to all of the above, regardless of how many dimensions they have.

## Starting With Tensors

In [ ]:
import torch
print(torch.__version__)

2.9.0+cpu


## Introduction to tensor

### creating a tensor




In [ ]:
# Scalar
import torch
scalar = torch.tensor(9)
scalar

tensor(9)

* In data science libraries like NumPy and PyTorch, .ndim is an attribute that tells you the number of dimensions (or axes) a data object has.



In [ ]:
scalar.ndim


0

In [ ]:
# getting tensor back as python int
scalar.item()

9

In [ ]:
# Vector
vector = torch.tensor([9,8])
vector

tensor([9, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

## Creating **MATRIX** in pytorch

In [ ]:
# A 2x3 Matrix (2 rows, 3 columns)
data = [[1, 2, 3],
        [4, 5, 6]]

MATRIX = torch.tensor(data)

MATRIX


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
MATRIX[1]

tensor([4, 5, 6])

In [ ]:
MATRIX.shape

torch.Size([2, 3])

##**TENSOR**

In [ ]:
TENSOR = torch.tensor([[[[1,2,3],
                        [7,8,9],
                        [8,9,5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [7, 8, 9],
          [8, 9, 5]]]])

### Understanding this Tensor

**1. Why is `.ndim` 4?**
You can determine dimensions by counting the opening brackets `[` before the first number appears:
* `[` (1st dim)
* `[` (2nd dim)
* `[` (3rd dim)
* `[` (4th dim)
* `1` (The data starts here)

**2. Why is `.shape` [1, 1, 3, 3]?**
This specific shape corresponds to a common image format in Deep Learning:
* **Batch Size: 1** (1 image in this group)
* **Channels: 1** (1 color channel, e.g., Grayscale)
* **Height: 3** (3 pixels high)
* **Width: 3** (3 pixels wide)

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[[1, 2, 3],
         [7, 8, 9],
         [8, 9, 5]]])

### Random Tensors
In machine learning and data science, random tensors are essentially multi-dimensional arrays filled with random numbers. While it might seem counterintuitive to start with "random" values, they are the vital "seed" that allows computers to learn.

The primary reason we use random tensors is to break symmetry and provide a starting point for optimization.

1. Breaking Symmetry: If all neurons start with the same value (like 0), they will all learn the exact same thing. Randomness ensures every neuron starts unique so they can "specialize" in different patterns.

2. A Starting Point: To use Gradient Descent (the way AI learns), the model needs a place to start on the "map." A random tensor places the model at a random spot so it can begin trekking toward the best solution.

3. Preventing Stagnation: Randomness helps the model avoid getting "stuck" in a poor solution early on, giving it a better chance to find the most accurate result.

In [ ]:
# Cereating a random tensors
import torch
random_tensor = torch.rand(2 ,3 , 3)
random_tensor

tensor([[[0.1278, 0.8128, 0.5431],
         [0.8348, 0.8550, 0.5018],
         [0.9179, 0.0087, 0.0491]],

        [[0.5681, 0.9427, 0.0860],
         [0.0745, 0.4487, 0.2392],
         [0.4129, 0.3686, 0.0739]]])

In [ ]:
random_tensor.ndim

3

In [2]:
# Creating a zero tensor
import torch
zero_tensor = torch.zeros(3,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
import torch
random_tensor = torch.rand(3, 4)
zero_tensor = torch.zeros(3, 4)
# Now perform the element-wise multiplication
zero_tensor * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# Crearting all ones (Identity)
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
ones_tensor.dtype


torch.float32

In [10]:
ones_tensor * random_tensor

tensor([[0.7969, 0.2885, 0.8048, 0.5893],
        [0.0354, 0.3811, 0.8317, 0.2873],
        [0.8515, 0.1075, 0.7812, 0.2722]])

In [6]:
random_tensor.dtype

torch.float32

Creating a range of Tensors and Tensor-like

In [15]:
one_to_ten = torch.arange(1 , 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


### Difference between `torch.arange()` and `torch.range()`

**`torch.arange(start, end, step)`**
Generates values starting from `start` (inclusive) up to `end` (exclusive), using a given step size.
It behaves like Python’s built-in `range()` but works for tensors and supports floating-point steps.
This is the recommended and standard way to generate ranges in PyTorch.

**`torch.range(start, end, step)`**
Generates values from `start` to `end`, including both endpoints.
This function is deprecated, may be removed in future versions, and can cause floating-point precision issues.
It should not be used in new code.

---

### Comparison Table

| Feature             | torch.arange() | torch.range() |
| ------------------- | -------------- | ------------- |
| End included        | No             | Yes           |
| Deprecated          | No             | Yes           |
| Floating-point safe | Yes            | Risky         |
| Recommended         | Yes            | No            |

---

### Recommendation

Always use `torch.arange()` and avoid `torch.range()`.


In [16]:
# Creating Tensors like
ten_Zeros = torch.zeros_like(input=one_to_ten)
ten_Zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

`torch.zeros_like(input=one_to_ten)` creates a new tensor filled with zeros that has the **same shape, data type, and device** as the tensor `one_to_ten`.

`ten_Zeros` stores this new zero tensor, so it can be used later for computations while preserving the structure of `one_to_ten`.


---

## Tensor Data Types (dtypes)

A tensor’s **data type (dtype)** defines what kind of values the tensor can store and how much memory each value uses.

### 1. Integer Types

Used for whole numbers (no decimals).

* `torch.int8` — 8-bit signed integer
* `torch.uint8` — 8-bit unsigned integer
* `torch.int16` — 16-bit signed integer
* `torch.int32` — 32-bit signed integer
* `torch.int64` — 64-bit signed integer (default for integer tensors)

These are typically used for indexing, counts, or discrete values.

---

### 2. Floating-Point Types

Used for real numbers (with decimals).

* `torch.float16` — half precision
* `torch.float32` — single precision (default for float tensors)
* `torch.float64` — double precision

Floating-point tensors are mainly used for neural networks, scientific computing, and optimization.

---

### 3. Boolean Type

Used for logical values.

* `torch.bool` — stores `True` or `False`

Commonly used for masks and condition filtering.

---

### 4. Complex Types

Used for complex numbers.

* `torch.complex64` — complex with 32-bit real and imaginary parts
* `torch.complex128` — complex with 64-bit real and imaginary parts

Used in signal processing, physics, and advanced mathematics.

---

## Summary Table

| Category | Data Type                         | Use Case                     |
| -------- | --------------------------------- | ---------------------------- |
| Integers | `int8`, `int16`, `int32`, `int64` | Counting, indexing           |
| Floats   | `float16`, `float32`, `float64`   | ML models, continuous values |
| Boolean  | `bool`                            | Masks, conditions            |
| Complex  | `complex64`, `complex128`         | Signal processing, physics   |

---

## Important Notes

* The default integer dtype is `torch.int64`.
* The default floating dtype is `torch.float32`.
* Choosing the right dtype helps save memory and improve performance.
* Lower precision (like `float16`) is faster but less accurate.


In [20]:
# Integer type
a = torch.tensor([1, 2, 3], dtype=torch.int8)
b = torch.tensor([1, 2, 3], dtype=torch.int16)
c = torch.tensor([1, 2, 3], dtype=torch.int32)
d = torch.tensor([1, 2, 3], dtype=torch.int64)

print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)
print(d, d.dtype)


tensor([1, 2, 3], dtype=torch.int8) torch.int8
tensor([1, 2, 3], dtype=torch.int16) torch.int16
tensor([1, 2, 3], dtype=torch.int32) torch.int32
tensor([1, 2, 3]) torch.int64


In [22]:
# Float Type
e = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float16)
f = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float32)
g = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float64)

print(e, e.dtype)
print(f, f.dtype)
print(g, g.dtype)


tensor([1.5000, 2.5000, 3.5000], dtype=torch.float16) torch.float16
tensor([1.5000, 2.5000, 3.5000]) torch.float32
tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64) torch.float64


In [23]:
# Boolean Type
h = torch.tensor([True, False, True], dtype=torch.bool)
print(h, h.dtype)


tensor([ True, False,  True]) torch.bool


In [24]:
# Complex Type
i = torch.tensor([1+2j, 3+4j], dtype=torch.complex64)
j = torch.tensor([1+2j, 3+4j], dtype=torch.complex128)

print(i, i.dtype)
print(j, j.dtype)


tensor([1.+2.j, 3.+4.j]) torch.complex64
tensor([1.+2.j, 3.+4.j], dtype=torch.complex128) torch.complex128


In [21]:
# Converstion Type
x = torch.tensor([1, 2, 3])

print(x.dtype)

x_float = x.float()
x_double = x.double()
x_bool = x.bool()

print(x_float.dtype)
print(x_double.dtype)
print(x_bool.dtype)


torch.int64
torch.float32
torch.float64
torch.bool


---

Let’s understand **what “8-bit, 16-bit, 32-bit, 64-bit” actually mean in tensor data types**.

---

## What does “bit” mean here?

A **bit (binary digit)** is the smallest unit of memory.
It can be either `0` or `1`.

When we say:

* `int8` → **8 bits per value**
* `int16` → **16 bits per value**
* `float32` → **32 bits per value**
* `float64` → **64 bits per value**

…it means **how many bits of memory are used to store one single number**.

---

## Why does this matter?

Because the number of bits controls:

1. **How large or precise a number can be**
2. **How much memory the tensor uses**
3. **How fast computations are**

---

## Bit size → range & precision

### Integer types

| Type  | Bits            | Range                    |
| ----- | --------------- | ------------------------ |
| int8  | 8 bits          | −128 to 127              |
| uint8 | 8 bits unsigned | 0 to 255                 |
| int16 | 16 bits         | −32,768 to 32,767        |
| int32 | 32 bits         | −2 billion to +2 billion |
| int64 | 64 bits         | very large range         |

More bits → larger numbers possible.

---

### Floating-point types

Floating numbers use bits for:

* sign (positive/negative),
* exponent (scale),
* mantissa (precision).

| Type    | Bits    | Approx Precision   |
| ------- | ------- | ------------------ |
| float16 | 16 bits | ~3 decimal digits  |
| float32 | 32 bits | ~7 decimal digits  |
| float64 | 64 bits | ~15 decimal digits |

More bits → more accurate decimal representation.

---

## Memory example

Suppose you have 1 million numbers:

| Type    | Bits per value | Memory |
| ------- | -------------- | ------ |
| int8    | 8 bits         | ~1 MB  |
| float32 | 32 bits        | ~4 MB  |
| float64 | 64 bits        | ~8 MB  |

So choosing the right dtype can save a lot of memory.

---

## Simple intuition

Think of **bits like the number of boxes you have to store information**:

* 8 boxes → you can store small things, fast, cheap.
* 64 boxes → you can store very detailed, very big things, but slower and costly.

---

## One-line summary

**The “bit” size tells you how much memory one tensor element uses, which directly controls the range, precision, speed, and memory usage of your tensor.**

If you want, I can explain how GPUs prefer `float16` or how mixed-precision training uses this — just tell me
